use std::collections::HashMap;

use tracing::{error, info, warn};
use uuid::Uuid;

use crate::db::Db;
use crate::db::models::{
    Event, EventSeverity, ExecutionStatus, ExtractionRule, Job, OutputAssertion, OutputTrigger,
};

/// Run extraction rules against stdout, returning extracted key-value pairs.
pub fn run_extractions(stdout: &str, rules: &[ExtractionRule]) -> HashMap<String, String> {
    let mut results = HashMap::new();
    for rule in rules {
        if let Some(value) = extract_value(stdout, &rule.pattern, &rule.rule_type) {
            results.insert(rule.name.clone(), value);
        }
    }
    results
}

fn extract_value(stdout: &str, pattern: &str, rule_type: &str) -> Option<String> {
    match rule_type {
        "regex" => extract_regex(stdout, pattern),
        "jsonpath" => extract_jsonpath(stdout, pattern),
        _ => None,
    }
}

/// Maximum allowed regex pattern length to prevent ReDoS.
const MAX_REGEX_PATTERN_LEN: usize = 1024;

fn extract_regex(stdout: &str, pattern: &str) -> Option<String> {
    if pattern.len() > MAX_REGEX_PATTERN_LEN {
        tracing::warn!("regex pattern too long ({} chars), skipping", pattern.len());
        return None;
    }
    let re = regex::Regex::new(pattern).ok()?;
    let caps = re.captures(stdout)?;
    // Try named groups first, then group 1
    for name in re.capture_names().flatten() {
        if let Some(m) = caps.name(name) {
            return Some(m.as_str().to_string());
        }
    }
    caps.get(1).map(|m: regex::Match| m.as_str().to_string())
}

fn extract_jsonpath(stdout: &str, path: &str) -> Option<String> {
    let parsed: serde_json::Value = serde_json::from_str(stdout.trim()).ok()?;
    // Simple dot-notation traversal: $.results.count -> ["results", "count"]
    let path = path.strip_prefix("$.").unwrap_or(path);
    let keys: Vec<&str> = path.split('.').collect();
    let mut current = &parsed;
    for key in keys {
        current = current.get(key)?;
    }
    match current {
        serde_json::Value::String(s) => Some(s.clone()),
        serde_json::Value::Null => None,
        other => Some(other.to_string()),
    }
}

/// Run assertions against stdout. Returns a list of failure messages for patterns NOT found.
pub fn run_assertions(stdout: &str, assertions: &[OutputAssertion]) -> Vec<String> {
    let mut failures = Vec::new();
    for assertion in assertions {
        let found = if let Ok(re) = regex::Regex::new(&assertion.pattern) {
            re.is_match(stdout)
        } else {
            stdout.contains(&assertion.pattern)
        };
        if !found {
            let msg = assertion.message.clone().unwrap_or_else(|| {
                format!(
                    "expected pattern '{}' not found in output",
                    assertion.pattern
                )
            });
            failures.push(msg);
        }
    }
    failures
}

/// Run trigger patterns against stdout and stderr, returning matched (pattern, severity) pairs.
pub fn run_triggers(
    stdout: &str,
    stderr: &str,
    triggers: &[OutputTrigger],
) -> Vec<(String, String)> {
    let mut matches = Vec::new();
    for trigger in triggers {
        let matched = if let Ok(re) = regex::Regex::new(&trigger.pattern) {
            re.is_match(stdout) || re.is_match(stderr)
        } else {
            // Fall back to substring match
            stdout.contains(&trigger.pattern) || stderr.contains(&trigger.pattern)
        };
        if matched {
            matches.push((trigger.pattern.clone(), trigger.severity.clone()));
        }
    }
    matches
}

/// Process all output rules for a completed execution: extractions (with variable write-back),
/// assertions, and triggers. Returns events generated by trigger matches.
pub fn process_post_execution(
    db: &Db,
    job: &Job,
    exec_id: Uuid,
    stdout: &str,
    stderr: &str,
    exec_status: ExecutionStatus,
) -> Vec<Event> {
    let mut events = Vec::new();
    let rules = match job.output_rules {
        Some(ref r) => r,
        None => return events,
    };

    // Extractions
    if !rules.extractions.is_empty() {
        let extracted = run_extractions(stdout, &rules.extractions);
        if !extracted.is_empty() {
            if let Err(e) = db.update_execution_extracted(exec_id, &serde_json::json!(extracted)) {
                warn!("failed to update extracted values for {}: {}", exec_id, e);
            }
            // Write-back: update global variables for rules with write_to_variable
            for rule in &rules.extractions {
                if let Some(ref var_name) = rule.write_to_variable
                    && let Some(value) = extracted.get(&rule.name)
                {
                    if let Err(e) = db.upsert_variable(var_name, value) {
                        error!("failed to write variable {}: {}", var_name, e);
                    } else {
                        info!("variable {} updated from extraction", var_name);
                    }
                }
            }
        }
    }

    // Assertions — only on successful executions
    if exec_status == ExecutionStatus::Succeeded && !rules.assertions.is_empty() {
        let failures = run_assertions(stdout, &rules.assertions);
        if !failures.is_empty() {
            let msg = failures.join("; ");
            if let Err(e) = db.fail_execution_assertion(exec_id, &msg) {
                warn!("failed to update assertion failure for {}: {}", exec_id, e);
            }
            warn!("execution {} failed assertion: {}", exec_id, msg);
        }
    }

    // Triggers
    let matches = run_triggers(stdout, stderr, &rules.triggers);
    for (pattern, severity) in &matches {
        let sev = match severity.as_str() {
            "error" => EventSeverity::Error,
            "warning" => EventSeverity::Warning,
            "success" => EventSeverity::Success,
            _ => EventSeverity::Info,
        };
        let event = Event {
            id: Uuid::new_v4(),
            kind: "output.matched".to_string(),
            severity: sev,
            message: format!(
                "Output pattern matched: '{}' in job '{}'",
                pattern, job.name
            ),
            job_id: Some(job.id),
            agent_id: None,
            api_key_id: None,
            api_key_name: None,
            details: None,
            timestamp: chrono::Utc::now(),
        };
        if let Err(e) = db.insert_event(&event) {
            warn!("failed to insert output trigger event: {}", e);
        }
        events.push(event);
    }

    events
}
